### ISSUE TITLE
Option for disable warning

### ISSUE THREAD

**Issue by sagitt** [azogue/fasthue#16]
what do you think for an option to disable these logs?
![Schermata 2020-11-19 alle 14 21 18](https://user-images.githubusercontent.com/169086/99671601-8a4ef200-2a72-11eb-9eed-d71e2b28a9b3.png)

**Comment by azogue** [comment]
Yeah, I suppose those logs could move to "INFO" level...

In the meantime, you could always ignore (or show in more detail) any component by setting the log level for it, in `configuration.yaml`:

```yaml
logger:
  default: warn
  logs:
    custom_components.fasthue: error
```
With that config, no warning logs would appear :)

But I'll hide those anyway. Sorry for the late answer :(
